// ⚠️  Auto-generated by scripts/apply-branding.mjs — do not edit directly.
// To update branding, edit app.config.mjs and run: pnpm run brand

export const APP_NAME           = 'EasiestClaw'
export const APP_ID             = 'com.EasiestClaw.desktop'
export const SETTINGS_DIR_NAME  = 'EasiestClaw-desktop'
export const FIREWALL_RULE_NAME = 'EasiestClaw'
